name: 'Harley Adventures '
favicon: null
layout_spectrum: 1
typography_spectrum: 0.10131
title: Harley Adventures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#282129'
    - '#ecebe9'
    - '#4d3942'
    - '#9b847c'
    - '#d1beaf'
  brandStrength: 1
  lightness: 0.5507927290163934
  saturation: 0.5732630854472518
  rhythmicContrast: 0.8110381613951176
purpose: []
