name: 'Harley Adventures '
favicon: null
layout_spectrum: 0.25244
typography_spectrum: 0.10131
title: Harley Adventures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#282129'
    - '#ecebe9'
    - '#4d3942'
    - '#9b847c'
    - '#d1beaf'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
