typography_spectrum: 0.10131
color:
  brandColors:
    - '#282129'
    - '#ecebe9'
    - '#4d3942'
    - '#9b847c'
    - '#d1beaf'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25244
analytics:
  google: null
  facebook: null
  twitter: null
name: 'Harley Adventures '
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Harley Adventures
description: I'm a GSP - follow my adventures!
purpose: []
