name: 'Harley Adventures '
favicon: null
layout_spectrum: 0.542607668088749
typography_spectrum: 0.4078564962837845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.23552541946992278
  lightness: 0.5507927290163934
  saturation: 0.5732630854472518
  rhythmicContrast: 0.8110381613951176
purpose: []
